directory: improve support for empty QueryResult (bug 1790047)
mozilla-conduit/mots pull request #27
Opened 2022-09-09 13:17 UTC by zzzeid

2022-09-09 14:53 UTC, dklawren approved these changes
LGTM and testing worked as expect. r=dkl

2022-09-12 15:13 UTC, cgsheeh requested changes

2022-09-12 15:32 UTC, zzzeid commented on tests/test_directory.py
> +    assert not (empty_result + other_empty_result)
That codepath is implicitly tested as part of `test_directory__Directory__query` and `test_directory__Directory__query_merging`, though I could add an explicit test here to test the basic case of non-empty `QueryResult`.

2022-10-24 14:58 UTC, cgsheeh approved these changes

2022-10-24 14:59 UTC, merged